[tool.black]
line-length = 125
skip-string-normalization = true
target-version = ["py312"]
organize_imports = true
exclude = '''
/(
    \.git
  | \.vscode
  | \.venv
  | \.venv.nosync
  | \.pytest_cache
  | venvm
  | migrations
)/
'''

[tool.isort]
profile = "black"
combine_as_imports = true
combine_star = true
line_length = 125
skip = [
  "venv",
  ".venv",
  ".venv.nosync",
  ".git",
  ".vscode",
  ".pytest_cache",
  "migrations",
]

[tool.mypy]
strict = true

[[tool.mypy.overrides]]
module = ["django.*", "rest_framework.*", "django_filters.rest_framework.*"]
ignore_missing_imports = true

[[tool.mypy.overrides]]
module = ["apps.*.migrations.*", "api.migrations.*"]
ignore_errors = true