# Generated by Django 5.0 on 2023-12-28 12:05

from django.db import migrations, models


class Migration(migrations.Migration):  # type: ignore
    initial = True

    dependencies: list[tuple[str, ...]] = []

    operations = [
        migrations.CreateModel(
            name='ProductTag',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
    ]
