# Generated by Django 5.0 on 2023-12-31 10:57

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('product_tags', '0002_initial'),
        ('products', '0005_alter_product_table_alter_productimage_table_and_more'),
        ('tags', '0002_alter_tag_options_alter_tag_table'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='producttag',
            unique_together={('product', 'tag')},
        ),
        migrations.AlterModelTable(
            name='producttag',
            table='product_tags',
        ),
    ]
