# Generated by Django 5.0 on 2023-12-29 10:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('carts', '0001_initial'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='product',
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, related_name='cart_items', to='products.product'
            ),
        ),
    ]
