# Generated by Django 5.0 on 2023-12-31 10:57

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('carts', '0003_alter_cartitem_product'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='cart',
            table='carts',
        ),
        migrations.AlterModelTable(
            name='cartitem',
            table='cart_items',
        ),
    ]
