# Generated by Django 5.0 on 2023-12-27 17:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):  # type: ignore
    dependencies = [
        ('orders', '0002_orderitem_created_at_orderitem_price_and_more'),
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='payments.payment'),
            preserve_default=False,
        ),
    ]
