# Generated by Django 5.0 on 2023-12-31 07:11

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('orders', '0003_alter_orderitem_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='status',
        ),
    ]
