# Generated by Django 5.0 on 2023-12-28 12:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):  # type: ignore
    dependencies = [
        ('customers', '0001_initial'),
        ('orders', '0003_remove_order_customer_id_order_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='customer',
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='orders',
                to='customers.customer',
            ),
        ),
    ]
