# Generated by Django 5.0 on 2023-12-27 17:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):  # type: ignore
    dependencies = [
        ('orders', '0003_order_payment'),
        ('payments', '0002_remove_payment_order_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment',
            field=models.OneToOneField(
                default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='payments.payment'
            ),
        ),
    ]
