# Generated by Django 5.0 on 2023-12-28 12:30

from django.db import migrations


class Migration(migrations.Migration):  # type: ignore
    dependencies = [
        ('orders', '0004_alter_order_customer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='order_id',
            new_name='order',
        ),
    ]
