# Generated by Django 5.0 on 2023-12-28 12:44

from django.db import migrations, models


class Migration(migrations.Migration):  # type: ignore
    dependencies = [
        ('orders', '0005_rename_order_id_orderitem_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
