# Generated by Django 5.0 on 2023-12-28 12:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):  # type: ignore
    dependencies = [
        ('orders', '0007_alter_order_payment'),
        ('payments', '0002_alter_payment_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment',
            field=models.OneToOneField(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='order',
                to='payments.payment',
            ),
        ),
    ]
