# Generated by Django 5.0 on 2023-12-28 12:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):  # type: ignore
    initial = True

    dependencies: list[tuple[str, ...]] = [
        ('genres', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductGenre',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('genre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='genres.genre')),
            ],
        ),
    ]
