# Generated by Django 5.0 on 2023-12-31 10:57

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('genres', '0003_alter_genre_options_alter_genre_table'),
        ('product_genres', '0002_initial'),
        ('products', '0005_alter_product_table_alter_productimage_table_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='productgenre',
            unique_together={('product', 'genre')},
        ),
        migrations.AlterModelTable(
            name='productgenre',
            table='product_genres',
        ),
    ]
