# Generated by Django 5.0 on 2023-12-28 17:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='password_hash',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='customer',
            name='salt',
            field=models.CharField(max_length=128),
        ),
    ]
