# Generated by Django 5.0 on 2023-12-30 20:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('customers', '0002_customeraddress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customeraddress',
            name='customer',
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, related_name='address', to='customers.customer'
            ),
        ),
    ]
