# Generated by Django 5.0 on 2023-12-27 17:33

from django.db import migrations, models


class Migration(migrations.Migration):  # type: ignore
    initial = True

    dependencies = []  # type: ignore

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('amount', models.IntegerField()),
                ('provider', models.CharField(max_length=128)),
                ('order_id', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
