# Generated by Django 5.0 on 2023-12-31 10:57

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='payment',
            table='payments',
        ),
    ]
