# Generated by Django 5.0 on 2023-12-27 17:39

from django.db import migrations


class Migration(migrations.Migration):  # type: ignore
    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='order_id',
        ),
    ]
