# Generated by Django 5.0 on 2023-12-27 15:47

from django.db import migrations, models


class Migration(migrations.Migration):  # type: ignore
    initial = True

    dependencies = []  # type: ignore

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('street_address', models.CharField(max_length=512)),
                ('province', models.CharField(max_length=128)),
                ('district', models.CharField(max_length=128)),
                ('postal_code', models.CharField(max_length=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
