# Generated by Django 5.0 on 2023-12-29 17:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('products', '0002_alter_productimage_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
