# Generated by Django 5.0 on 2023-12-31 10:57

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('products', '0004_alter_productimage_image'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='product',
            table='products',
        ),
        migrations.AlterModelTable(
            name='productimage',
            table='product_images',
        ),
        migrations.AlterModelTable(
            name='productinventory',
            table='product_inventories',
        ),
    ]
