# Generated by Django 5.0 on 2023-12-30 18:50

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('genres', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='genre',
            options={},
        ),
    ]
